version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
