apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blog-backend-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog-backend  # What are we scaling?
  minReplicas: 2        # Never drop below 2 pods (for safety)
  maxReplicas: 5        # Never go above 5 pods (to save money/resources)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # The trigger: 50% of our 100m request
