apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: dev
spec:
  # clusterIP: None makes this a Headless Service. 
  # This allows direct access to individual pods in the StatefulSet (mongodb-0, mongodb-1, etc.)
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: dev
  labels:
    app: mongodb
spec:
  # The serviceName must match the name of the Headless Service we created above.
  serviceName: "mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
  # volumeClaimTemplates is the 'StatefulSet way' to manage storage.
  # Kubernetes will automatically create a PVC for each pod (e.g. mongodb-storage-mongodb-0).
  volumeClaimTemplates:
  - metadata:
      name: mongodb-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
